import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// Vite configuration for the Braincast app.
// This file sets up the React plugin and specifies the build output
// directory. Vercel will detect the build output automatically when
// deploying a static site generated by Vite.
export default defineConfig({
  plugins: [react()],
  build: {
    outDir: 'dist',
    emptyOutDir: true
  }
});
